import React, { useState, useEffect } from 'react';
import HistoryListItem from "./history-list-item";

function HistoryList() {

    const [coverLetterHistory, setCoverLetterHistory] = useState([]);

    useEffect(() => {
        // Fetch list of cover letters already generated by the user
        fetch('/users/1/generated-docs-history')
            .then(response => response.json())
            .then(data => setCoverLetterHistory(data))
            .catch(error => console.error('Error fetching list:', error));
    }, []); // Empty dependency array means this effect runs once on mount


    return (
        <div className='p-5 h-full bg-gradient-to-b from-blue-500 overscroll-contain'>
            {coverLetterHistory.map(doc => (
                <HistoryListItem company={doc.company} position={doc.position} dateCreated={doc.dateCreated} />
            ))}
        </div>
    );
}

export default HistoryList;